version: 0.0
os: linux
files:
  - source: /
    destination: /opt/prometheus
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: root

  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 180
      runas: root

  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 180
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 180
      runas: root
