scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: 
        - localhost:9090

  - job_name: spring-actuator
    metrics_path: /actuator/prometheus
    scheme: http
    scrape_interval: 15s
    ec2_sd_configs:
      - region: ap-northeast-2
        port: 80
        filters:
          - name: tag:Monitoring
            values: 
              - enabled
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
      - source_labels: [__meta_ec2_private_ip]
        regex: (.*)
        replacement: ${1}:10090
        action: replace
        target_label: __address__
      - source_labels: [__meta_ec2_tag_group]
        target_label: group
      - source_labels: [__meta_ec2_instance_type]
        target_label: instance_type
