global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-server'
    metrics_path: '/server/actuator/prometheus'
    scheme: https
    static_configs:
      - targets: ['api.beforegoing.store']

    basic_auth:
      username: ${PROMETHEUS_USERNAME}
      password: ${PROMETHEUS_PASSWORD}
